export const NIGERIAN_BANK_CODES: Record<string, string> = {
  "access bank": "044",
  "citibank": "023",
  "ecobank": "050",
  "fidelity bank": "070",
  "first bank": "011",
  "first city monument bank": "214",
  "first city monument bank (fcmb)": "214",
  "fcmb": "214",
  "globus bank": "00103",
  "gtbank": "058",
  "guaranty trust bank": "058",
  "heritage bank": "030",
  "jaiz bank": "301",
  "keystone bank": "082",
  "kuda bank": "50211",
  "moniepoint mfb": "50515",
  "opay": "999992",
  "optimus bank": "107",
  "palmpay": "999991",
  "parallex bank": "526",
  "polaris bank": "076",
  "premium trust bank": "105",
  "providus bank": "101",
  "rubies mfb": "125",
  "signature bank": "106",
  "stanbic ibtc bank": "221",
  "stanbic ibtc": "221",
  "standard chartered bank": "068",
  "sterling bank": "232",
  "suntrust bank": "100",
  "taj bank": "302",
  "titan trust bank": "102",
  "union bank": "032",
  "uba": "033",
  "united bank for africa": "033",
  "unity bank": "215",
  "vfd microfinance bank": "566",
  "wema bank": "035",
  "zenith bank": "057",
};

export const FALLBACK_BANKS = [
  "Access Bank",
  "Citibank",
  "Ecobank",
  "Fidelity Bank",
  "First Bank",
  "First City Monument Bank (FCMB)",
  "Globus Bank",
  "GTBank",
  "Heritage Bank",
  "Jaiz Bank",
  "Keystone Bank",
  "Kuda Bank",
  "Moniepoint MFB",
  "OPay",
  "Optimus Bank",
  "Palmpay",
  "Parallex Bank",
  "Polaris Bank",
  "Premium Trust Bank",
  "Providus Bank",
  "Rubies MFB",
  "Signature Bank",
  "Stanbic IBTC Bank",
  "Standard Chartered Bank",
  "Sterling Bank",
  "SunTrust Bank",
  "TAJ Bank",
  "Titan Trust Bank",
  "Union Bank",
  "UBA",
  "Unity Bank",
  "VFD Microfinance Bank",
  "Wema Bank",
  "Zenith Bank",
  "Other",
];
